grpc:
  server:
    port: 59091
    reflection-service-enabled: true

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcTransactionManagerAutoConfiguration


logging:
  level:
    #    io.grpc: DEBUG
    #    net.devh.boot.grpc: DEBUG
    ru:
      yandex:
        practicum:
          telemetry:
            collector:
              controller:
                DEBUG
              handler:
                DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level --- [%thread] %logger{36} : %msg%n"

kafka:
  producer:
    bootstrap-servers: localhost:9092
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: serializer.AvroSerializer