@namespace("ru.yandex.practicum.kafka.telemetry.event")
protocol SensorsSnapshotProtocol {

    import idl "SensorEvent.avdl";

    record SensorStateAvro {
        timestamp_ms timestampMs;
        union {
            ClimateSensorAvro,
            LightSensorAvro,
            MotionSensorAvro,
            SwitchSensorAvro,
            TemperatureSensorAvro
        } data;
    }

    record SensorsSnapshotAvro {
        string hubId;
        timestamp_ms timestampMs;
        map<SensorStateAvro> sensorsState;
    }
}